### ISSUE TITLE
Not working with Grav's Admin Panel

### ISSUE THREAD

**Issue by jpfleury** [giansi/grav-plugin-social-buttons#2]
The plugin SocialButtons can't be configured using the new [Grav's Admin Panel](https://github.com/getgrav/grav-plugin-admin). For example, if we go to the settings page of the plugin (url `/admin/plugins/socialbuttons`) and click on *Save*, there's the following error:

> **Validation failed:** buttons is not defined in blueprints

According to a Grav developer: "These plugins just need to get updated with appropriate blueprint files so they will work in the admin plugin."

My config: Grav v0.9.39, Admin Panel v0.4.2, SocialButtons v1.0.0

**Comment by giansi** [comment]
Fixed with 1.0.2 release
