### ISSUE TITLE
Plugin no longer working

### ISSUE THREAD

**Issue by umbergerba** [giansi/grav-plugin-social-buttons#6]
Greetings,

Since I updated to the latest version of GRAV, the plugin no longer works (but it was before).

Suggestions?

Brian U.

**Comment by umbergerba** [comment]
Doh! ... Fixed.

**Comment by umbergerba** [comment]
In addition to the plugin not working anymore, when saving I get the following error ...

![screen shot 2015-11-20 at 11 58 24 pm](https://cloud.githubusercontent.com/assets/5008228/11317002/4215402c-8fe3-11e5-8b00-eb2eb48a491f.png)

**Comment by giansi** [comment]
Do you mean, Grav 1.0.0-RC5?

**Comment by umbergerba** [comment]
Yes.

**Comment by umbergerba** [comment]
Occurring on some other grav sites I have too.

**Comment by giansi** [comment]
Just downloaded the latest Grav release from their website, added the plugin and everything is fine for me: have you updated the plugin to latest release?

**Comment by seb-vial** [comment]
You might need to remove your `/user/config/plugins/socialbuttons.yaml` file, It does not have the same form as the original one
